version: "3"
services:
  proxy:
    build: ./balancer-app
    ports:
      - "5000:5000"
    environment:
      - HOSTS=http://web1:8000,http://web2:8000,http://web3:8000
  web1:
    build: ./numbers-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
  web2:
    build: ./numbers-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
  web3:
    build: ./numbers-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
  db:
    image: postgres
    volumes:
      - data_base:/var/lib/postgresql/data
volumes:
  data_base:
